controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
# api_carrito:
#   path: /api/carrito
#   controller: App\Controller\CarritoController::obtenerCarrito
#   methods: GET